train_file: ['D:\study\NLP\lab\project\data\annotation\vqa_train.json']
val_file: ['D:\study\NLP\lab\project\data\annotation\vqa_val.json']
test_file: ['D:\study\NLP\lab\project\data\annotation\vqa_test.json']
answer_list: 'D:\study\NLP\lab\project\data\annotation\answer_list.json'

vqa_root: 'D:\study\NLP\lab\project\data\image\val2014' #train2014/
vg_root: '/export/share/datasets/vision/visual-genome/'  #image/

train_mindrecord: '/data/MindRecord/train.mindrecord'
val_mindrecord: '/data/MindRecord/val.mindrecord'
test_mindrecord: '/data/MindRecord/test.mindrecord'

mindrecord_path: './data/MindRecord'

image_res: 384
batch_size_train: 32 
batch_size_test: 16 
k_test: 128

alpha: 0.4
distill: True
warm_up: True

eos: '[SEP]'

bert_config: 'configs/config_bert.json'

base_lr: 2e-5
warmup_ratio: 0.4
weight_decay: 0.02
momentum: 0.9
loss_scale: 1024
step_size: 100

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







